import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from './header';
import StoreProvider from './StoreProvider';
import ThemeClient from '@/themeProvider';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next Test',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const locale = await getLocale();
	const messages = await getMessages();
	return (
		<html lang={locale}>
			<StoreProvider>
				<ThemeClient>
					<NextIntlClientProvider messages={messages} locale={locale}>
						<body className={inter.className}>
							<Header />
							{children}
						</body>
					</NextIntlClientProvider>
				</ThemeClient>
			</StoreProvider>
		</html>
	);
}
