import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from './header';
import ThemeProvider from '@mui/material/styles/ThemeProvider';
import { createTheme } from '@mui/material';
import ThemeClient from '@/themeProvider';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next Test',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeClient>
				<body className={inter.className}>
					<Header />
					{children}
				</body>
			</ThemeClient>
		</html>
	);
}
