import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from './components/header';
import StoreProvider from './StoreProvider';
import ThemeClient from '../themeProvider';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next Test',
	description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<StoreProvider>
				<ThemeClient>
					<body className={inter.className}>
						<Header />
						{children}
					</body>
				</ThemeClient>
			</StoreProvider>
		</html>
	);
}

export default RootLayout;
